# Generated by Django 3.2.6 on 2021-08-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'Устройства оповещения'},
        ),
    ]
